name: science_based_meals
description: "A science-based meal planning app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.2
  json_annotation: ^4.8.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.6
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  form_validator: ^2.1.1
  image_picker: ^1.0.4
  http_parser: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
